baseURL = "https://licht.work/"
languageCode = "zh-cn"
title = "Licht"
theme = "hugo-theme-stack"

[permalinks]
page = "/:slug/"

[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true

[params.footer]
since = 2024

[params.dateFormat]

[params.sidebar]
compact = false
subtitle = "Licht's Blog"

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.png"

[params.article]
headingAnchor = false
math = false
toc = true
readingTime = true

    [params.article.license]
    enabled = false
    default = "Licensed under CC BY-NC-SA 4.0"

[params.comments]
enabled = true
provider = "giscus"

    [params.comments.giscus]
    repo = "LichtHong/licht.work"
    repoID = "R_kgDOMggDOQ"
    category = "giscus"
    categoryID = "DIC_kwDOMggDOc4CheUR"
    mapping = "og:title"
    lightTheme = "light"
    darkTheme = "dark"
    reactionsEnabled = 1
    emitMetadata = 0

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"

    [params.widgets.homepage.params]
    limit = 5

[[params.widgets.homepage]]
type = "categories"

    [params.widgets.homepage.params]
    limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

    [params.widgets.homepage.params]
    limit = 10

[[params.widgets.page]]
type = "toc"

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

[params.colorScheme]
toggle = true
default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[menu]
main = [ ]

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/LichtHong"

    [menu.social.params]
    icon = "brand-github"

[related]
includeNewer = true
threshold = 60
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 200

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4